### ISSUE TITLE
Server Crash on updating Mod

### ISSUE THREAD

**Issue by Dranemra** [Elrol/Server-Utilities#10] opened 2019-11-09 11:28 UTC
I updated to your new server Utilities from the Elrol's betas, and your mod crashes my server, it will not load. 
`[Server thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[07:25:07] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Elrol's Utilities (serverutilities) has failed to load correctly
§7An I/O error occured
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}
`

I've attached the following crash log in hopes you can clarify the situation.
[crash-2019-11-09_07.25.07-server.txt](https://github.com/Elrol/Server-Utilities/files/3827211/crash-2019-11-09_07.25.07-server.txt)

**Comment by Elrol** [comment] 2019-11-09 12:42
Many thanks for this, I am working right now on fixing it and will have it pushed in less then 30 min, running a few more tests to make sure everything is working. The last update was pushed early to fix the playerdata loading issue, but ended up having a few issues of its own, I have tested for about an hour now, killing bugs that popped up to make a more stable build. I am running the last test to make sure that the new autosave feature works as intended.

**Comment by Elrol** [comment] 2019-11-09 12:58
The file has been uploaded, please give it a try, and if it fixes the issue then feel free to close the issue. 
Sorry for the issue.

**Comment by Dranemra** [comment] 2019-11-09 14:13
Works great! 
Thanks alot, I'll be closing this ticket.
Sadly, due to a lack of proper grief protection, I've not fully opened my server to public at this time.

**Closed** 2019-11-09 14:13 UTC
Labels: To-Do, bug

**Comment by Elrol** [comment] 2019-11-09 14:17
I can understand that, I may look at making a claiming system in the mod before too long, either way, glad its fixed. If you have any other troubles, or suggestions, let me know :D
