### ISSUE TITLE
Description: Ticking memory connection

### ISSUE THREAD

**Issue by raziel23x** [Elrol/Server-Utilities#7] opened 2019-11-04 00:14 UTC
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/3/19 7:12 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at com.github.elrol.ElrolsUtilities.data.ServerData.getPlayerData(ServerData.java:32) ~[?:1.14.4-0.8.1] {re:classloading}
	at com.github.elrol.ElrolsUtilities.events.OnPlayerJoinHandler.onPlayerJoin(OnPlayerJoinHandler.java:25) ~[?:1.14.4-0.8.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_297_OnPlayerJoinHandler_onPlayerJoin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:43) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:206) ~[?:?] {re:classloading}
	at shadows.fastbench.net.HijackedPlayerList.func_72355_a(HijackedPlayerList.java:18) ~[?:2.1.4] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116) ~[?:?] {re:classloading,xf:fml:randompatches:RandomPatches ServerLoginNetHandler Transformer}
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:63) ~[?:?] {re:classloading,xf:fml:randompatches:RandomPatches ServerLoginNetHandler Transformer}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:224) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.elrol.ElrolsUtilities.data.ServerData.getPlayerData(ServerData.java:32)
	at com.github.elrol.ElrolsUtilities.events.OnPlayerJoinHandler.onPlayerJoin(OnPlayerJoinHandler.java:25)
	at net.minecraftforge.eventbus.ASMEventHandler_297_OnPlayerJoinHandler_onPlayerJoin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:43)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:206)
	at shadows.fastbench.net.HijackedPlayerList.func_72355_a(HijackedPlayerList.java:18)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:224)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@2421537f
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3501564680 bytes (3339 MB) / 7028080640 bytes (6702 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.80.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.80.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.80.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.80.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.80.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.80
	FML Language Providers: 
		javafml@28.1
		minecraft@1
		kotori_scala@2.13.1
	Mod List: 
		container-1.14.4-1.0.0.jar Container {container@1.14.4-1.0.0 DONE}
		ComPatchedStorage-1.14.4-2.1.4.jar ComPatchedStorage {compatchedstorage@2.1.4 DONE}
		CyclopsCore-1.14.4-1.5.5.jar Cyclops Core {cyclopscore@1.5.5 DONE}
		Wyrmroost-1.14.4-1.0.2.jar Wyrmroost {wyrmroost@1.0.2 DONE}
		upsizer-mc1.14.4-5.0b2.jar Upsizer {upsizer@5.0.0b2 DONE}
		techemistry-1.14.4-12.jar Techemistry {techemistry@1.14.4-12 DONE}
		Uppers-0.1.10.jar Uppers {uppers@0.1.10 DONE}
		EditSign-1.14.4-1.0.1+4.jar Edit Sign {edit_sign@1.0.1+4 DONE}
		SilentMechanisms-1.14.4-0.6.7+40.jar Silent's Mechanisms {silents_mechanisms@0.6.7+40 DONE}
		bambooeverything-1.14-1.4.0.jar Bamboo Everything {bambooeverything@1.14-1.4.0 DONE}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 DONE}
		KleeSlabs_1.14.4-7.4.7.jar KleeSlabs {kleeslabs@7.4.7 DONE}
		ChickenDropFeathers-2.0.jar Chicken Drop Feathers {chickendropfeathersmod@2.0 DONE}
		IronJetpacks-1.14.4-2.0.3.jar Iron Jetpacks {ironjetpacks@2.0.3 DONE}
		essentials-1.14.4-2.6.1.jar Essentials {essentials@1.14.4-2.6.1 DONE}
		Controlling-5.0.4.jar Controlling {controlling@5.0.4 DONE}
		Placebo-1.14.4-2.3.3.jar Placebo {placebo@2.3.3 DONE}
		globaldatapack-1.14.4-1.2.1.jar Dark Roleplay - Global Datapacks {globaldatapack@1.14.4-1.2 DONE}
		dankstorage-1.10a.jar Dank Storage {dankstorage@1.10a DONE}
		citadel-1.0.0.jar Citadel {citadel@1.0.0 DONE}
		WoolToString-1.14.2-1.0.0.jar WoolToString {wooltostring@1.0.0 DONE}
		TheVeggieWay-1.14.4-2.0.26.jar The Veggie Way {veggie_way@2.0.26 DONE}
		u_team_core-1.14.4-2.7.8.138.jar U Team Core {uteamcore@2.7.8.138 DONE}
		randompatches-1.14.4-1.19.1.1.jar RandomPatches {randompatches@1.14.4-1.19.1.1 DONE}
		buildinggadgets-3.1.1b.jar Building Gadgets {buildinggadgets@3.1.1b DONE}
		Apotheosis-1.14.4-2.4.4.jar Apotheosis {apotheosis@2.4.4 DONE}
		torchoptimizer-1.14.4-2.1.6.jar Torch Optimizer {torchoptimizer@1.14.4-2.1.6 DONE}
		ironshulkerboxes-1.14.4-3.1.12.jar Iron Shulker Boxes {ironshulkerbox@1.14.4-3.1.12 DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		WaterStrainer-1.14.4-7.0.2.jar Water Strainer {waterstrainer@1.14.4-7.0.2 DONE}
		A Block of Flint-1.0.jar A Block of Flint {flintblock@1.0 DONE}
		StoneChest-1.14.4-1.0.1.jar Stone Chest {stonechest@1.0.1 DONE}
		moreprog-1.14.4-0.4.4.jar MoreProgression {moreprogression@0.4.4 DONE}
		CarryOn MC1.14.4 v1.12.4.jar Carry On {carryon@1.12.4 DONE}
		JustEnoughResources-1.14.4-0.10.0.66.jar Just Enough Resources {jeresources@0.10.0.66 DONE}
		EnergeticSheep-1.14.4-1.1.6.jar EnergeticSheep {energeticsheep@1.1.6 DONE}
		dcintegration-1.1.2-1.14.jar Discord Integration {dcintegration@1.1.2 DONE}
		refinedstorage-1.7.jar Refined Storage {refinedstorage@1.7 DONE}
		peanutmod-1.0.2.jar Peanut Mod {peanutmod@1.0.2 DONE}
		useful_backpacks-1.14.4-1.7.4.46.jar Useful Backpacks {usefulbackpacks@1.7.4.46 DONE}
		torchmaster-2.0.0-rc1.jar Torchmaster {torchmaster@2.0.0-rc1 DONE}
		Compressium-1.0.12.jar Compressium {compressium@1.14-1.0.3 DONE}
		BiomesOPlenty-1.14.4-9.0.0.255-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.254 DONE}
		valkyrielib-3.0.0.8.jar ValkyrieLib {valkyrielib@3.0.0.8 DONE}
		SilentGear-1.14.4-1.4.3+68.jar Silent Gear {silentgear@1.4.3+68 DONE}
		extcaves-1.3.3.jar Extended Caves {extcaves@1.3.3 DONE}
		simplylight-0.9.0.jar Simply Light {simplylight@0.9.0 DONE}
		simplefarming-1.14.4-1.2.2.jar Simple Farming {simplefarming@1.14.4-1.2.2 DONE}
		LLOverlayReloaded-1.2.4-mc1.14.4.jar Light Level Overlay Reloaded {llor@1.2.4-mc1.14.4 DONE}
		lycanitesmobs-1.14.4-2.1.0.6.jar Lycanites Mobs {lycanitesmobs@1.0 DONE}
		portality-1.14.4-2.0.4-b0b3467.jar Portality {portality@2.0.4 DONE}
		corail_woodcutter-1.0.6-1.14.4.jar Corail Woodcutter {corail_woodcutter@1.0.6 DONE}
		RandomThings-MC1.14.4-5.0.1.jar Random Things {randomthings@5.0.1 DONE}
		RingOfBlink-1.14.4-1.0.20.jar Ring of Blink {ring_of_blink@1.0.20 DONE}
		enchxchg-1.14.4-5.0.0.jar Enchantments Exchanger {enchxchg@1.14.4-5.0.0 DONE}
		RingOfMiner-1.14.4-1.0.15.jar Ring of Miner {ring_of_miner@1.0.15 DONE}
		TorchBandolier-1.14.4-1.3.2+7.jar Torch Bandolier {torchbandolier@1.3.2+7 DONE}
		OreExcavation-1.6.141.jar Ore Excavation {oreexcavation@1.6.141 DONE}
		angelring-1.14.4-1.0.1.jar Angel Ring {angelring@1.0.1 DONE}
		f2l-0.2.1.jar Flesh 2 Leather {f2l@0.2.1 DONE}
		elevatorid-1.14.4-1.5.2.jar Elevator Mod {elevatorid@1.14.4-1.5.2 DONE}
		Gobber2-1.14.4-2.1.110.jar Gobber 2 {gobber2@2.1.110 DONE}
		tombstone-4.1.7-1.14.4.jar Corail Tombstone {tombstone@4.1.7 DONE}
		RingOfEnderchest-1.14.4-1.0.18.jar Ring of Enderchest {ring_of_enderchest@1.0.18 DONE}
		PowderPower-1.14.4-3.0.39.jar Powder Power {powder_power@3.0.39 DONE}
		cc-tweaked-1.14.4-1.85.0.jar CC: Tweaked {computercraft@1.85.0 DONE}
		tramplestopper-1.14.4-2.0.0.26-universal.jar Trample Stopper {tramplestopper@1.14.4-2.0.0.26-universal DONE}
		SBM-WoodenShears-1.14.4-1.0.0.jar SBM-Wooden Shears {woodenshears@1.0.0 DONE}
		YAMDA-4.1.1.jar YAMDA {yamda@4.1.1 DONE}
		Charm-1.14.4-1.3.4.jar Charm {charm@1.14.4-1.3.4 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		QuantumStorage-1.14.4-5.0.2.jar QuantumStorage {quantumstorage@NONE DONE}
		compact-2.6a.jar Compressed {compressed@2.6a DONE}
		Cyclic-1.14.4-0.0.12.jar Cyclic {cyclic@1.14.4-0.0.12 DONE}
		inventorysorter-1.14.4-16.2.0.jar Simple Inventory Sorter {inventorysorter@16.2.0 DONE}
		Cucumber-1.14.4-2.0.5.jar Cucumber Library {cucumber@2.0.5 DONE}
		bambooladders-1.14-1.0.0.jar Bamboo Ladders {bambooladders@1.14-1.0.0 DONE}
		craftingstation-2.1.1.jar Crafting Station {craftingstation@2.1.1 DONE}
		snad-1.14.4-1.7.10.27a.jar Snad {snad@1.7.10.27a DONE}
		Overloaded-1.14.4-0.0.78.jar Overloaded {overloaded@1.14.4-0.0.78 DONE}
		ParticleFixes-v1.1-1.14.4.jar Particle Fixes {particlefixes@1.1 DONE}
		jei-1.14.4-6.0.0.18.jar Just Enough Items {jei@6.0.0.18 DONE}
		metalbarrels-1.3d.jar Metal Barrels {metalbarrels@1.3d DONE}
		EverlastingAbilities-1.14.4-1.5.5.jar EverlastingAbilities {everlastingabilities@1.5.5 DONE}
		AttributeFix-1.14.4-3.0.2.jar AttributeFix {attributefix@3.0.2 DONE}
		caelus-FORGE-1.14.4-1.0.jar Caelus API {caelus@FORGE-1.14.4-1.0 DONE}
		Upgrade Aquatic Wave Three v6 - Beta 1.0.8.jar Upgrade Aquatic {upgrade_aquatic@1.0.7 DONE}
		reap-1.10.2.jar Reap Mod {reap@1.10.2 DONE}
		colytra-FORGE-1.14.4-2.0.jar Colytra {colytra@FORGE-1.14.4-2.0 DONE}
		create-mc1.14.4_v0.1.1a.jar Create {create@0.1.1a DONE}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 DONE}
		RingOfRepair-1.14.4-1.0.18.jar Ring of Repair {ring_of_repair@1.0.18 DONE}
		enviromats-2.0.0.9.jar Environmental Materials {enviromats@2.0.0.9 DONE}
		SimpleStorageNetwork-1.14.4-0.0.13.jar Simple Storage Network {storagenetwork@1.14.4-0.0.13 DONE}
		cursedearth-1.3a.jar Cursed Earth {cursedearth@1.3a DONE}
		DungeonCrawl-1.14.4-1.5.1.jar Dungeon Crawl {dungeoncrawl@1.5.1 DONE}
		DefaultSettings-1.14.x-1.3.5.jar DefaultSettings {defaultsettings@1.3.5 DONE}
		RingOfTeleport-1.14.4-1.0.16.jar Ring of Teleport {ring_of_teleport@1.0.16 DONE}
		alib-1.14.4-7.jar A Lib {alib@1.14.4-7 DONE}
		mcjtylib-1.14-3.5.10-alpha.jar McJtyLib {mcjtylib@1.14-3.5.10-alpha DONE}
		rftoolsbase-1.14-0.0.7-alpha.jar RFToolsBase {rftoolsbase@1.14-0.0.7-alpha DONE}
		rftoolsstorage-1.14-0.0.2-alpha.jar RFToolsStorage {rftoolsstorage@1.14-0.0.2-alpha DONE}
		A Block of Charcoal-1.2.jar A Block of Charcoal {charcoalblock@1.2 DONE}
		travellersboots-1.14.4-1.2.2.jar Traveller's Boots {travellersboots@1.2.2 DONE}
		rftoolspower-1.14-1.2.7-alpha.jar RFToolsPower {rftoolspower@1.14-1.2.7-alpha DONE}
		GemsPlusPlus-Forge-1.14.4-1.4.0.jar GemsPlusPlus {gemsplusplus@V1.4.0 DONE}
		firstaid-1.7.9.jar First Aid {firstaid@1.7.9 DONE}
		campfiretorches-1.14.4-1.0.3.jar Campfire Torches {campfiretorches@1.14.4-1.0.3 DONE}
		forge-1.14.4-28.1.80-universal.jar Forge {forge@28.1.80 DONE}
		ruins-1.14.4.4.jar Ruins {ruins@1.14.3.3 DONE}
		ColossalChests-1.14.4-1.7.4.jar ColossalChests {colossalchests@1.7.4 DONE}
		MysticalAgriculture-1.14.4-2.0.1.jar Mystical Agriculture {mysticalagriculture@2.0.1 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		SimpleDivingGear-3.0.3 mc 1.14.4.jar Simple Diving Gear {simpledivegear@3.0.3 mc 1.14.4 DONE}
		Elrols Utilities-1.14.4-0.8.1.jar Elrol's Utilities {elrolsutilities@1.14.4-0.8.1 DONE}
		CraftingTweaks_1.14.4-10.1.4.jar Crafting Tweaks {craftingtweaks@10.1.4 DONE}
		alchemistry-1.14.4-7.jar Alchemistry {alchemistry@1.14.4-7 DONE}
		forge-1.14.4-28.1.80-client.jar Minecraft {minecraft@1.14.4 DONE}
		extraanvils-2.4a.jar Extra Anvils {extraanvils@2.4a DONE}
		rftoolsutility-1.14-1.2.7-alpha.jar RFToolsUtility {rftoolsutility@1.14-1.2.7-alpha DONE}
		EnchantmentDescriptions-1.14.4-1.3.8.jar EnchantmentDescriptions {enchdesc@1.3.8 DONE}
		MouseTweaks-2.12-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.12 DONE}
		ToolBelt-1.14.4-1.12.5.jar Tool Belt {toolbelt@1.12.5 DONE}
		titanium-1.14.4-2.2.5.jar Titanium {titanium@2.2.5 DONE}
		EasySteel-1.14.4-1.0.47.jar Easy Steel & More {easy_steel@1.0.47 DONE}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 DONE}
		edibsgr_1.14-2.0.jar Edible Sugar {edibsgr@2.0 DONE}
		RingOfGrowth-1.14.4-1.0.18.jar Ring of Growth {ring_of_growth@1.0.18 DONE}
		forbidden_arcanus-1.14.4-1.4.jar Forbidden & Arcanus {forbidden_arcanus@1.14.4-1.4 DONE}
		ceilingtorch-1.14.4-v1.2.3.jar Ceiling Torch {ceilingtorch@v1.2.3 DONE}
		LargeFluidTank-14.8.4.jar FluidTank {fluidtank@14.8.4 DONE}
		spiketraps-1.1.jar Spike Traps {spiketraps@1.1 DONE}
		rftoolsbuilder-1.14-1.2.6-alpha.jar RFToolsBuilder {rftoolsbuilder@1.14-1.2.6-alpha DONE}
		FTBUtilitiesBackups-2.0.0.11.jar FTB Utilities: Backups {ftbbackups@2.0.0.11 DONE}
		chemlib-1.14.4-14.jar Chem Lib {chemlib@1.14.4-14 DONE}
		FastWorkbench-1.14.4-2.1.4.jar FastWorkbench {fastbench@2.1.4 DONE}
		StorageDrawers-1.14.4-6.0.5.jar Storage Drawers {storagedrawers@1.14.4-6.0.3 DONE}
		weapon_craftery-1.14.4-1.0-Beta-4.jar Weapon Craftery {weapon_craftery@1.14.4-1.0-Beta-4 DONE}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version DONE}
		Dirt2Path-1.0.0.jar Dirt2Path {d2p@1.0.0 DONE}
		tubesreloaded-1.14.4-1.1.0c.jar Tubes Reloaded {tubesreloaded@1.14.4-1.1.0c DONE}
		structurize-0.10.196-ALPHA.jar Structurize {structurize@0.10.196-ALPHA DONE}
		PickleTweaks-1.14.4-3.0.6.jar Pickle Tweaks {pickletweaks@3.0.6 DONE}
		minecolonies-0.10.513-ALPHA-universal.jar Minecolonies {minecolonies@0.10.513-ALPHA DONE}
		FastFurnace-1.14.4-2.2.4.jar FastFurnace {fastfurnace@2.2.4 DONE}
		[1.14.2-1.14.4]TorchBowMod_v1.5.jar TorchBowMod {torchbowmod@1.5 DONE}
		AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 DONE}
		Vampirism-1.14.4-1.6.0-alpha+20191021-1133.jar Vampirism {vampirism@1.6.0-alpha+20191021-1127 DONE, teamlapenlib@1.6.0-alpha+20191021-1127 DONE}
		RingOfAttraction-1.14.4-1.0.17.jar Ring of Attraction {ring_of_attraction@1.0.17 DONE}
		SilentGems-1.14.4-3.4.6+79.jar Silent's Gems 3 {silentgems@3.4.6+79 DONE}
		XL-Food-Mod-1.14.4-2.1.1.jar XL Food Mod {xlfoodmod@2.1.1 DONE}
		forgemod_VoxelMap-1.9.13b_for_1.14.4.jar VoxelMap {voxelmap@1.9.13 DONE}
		SolarGeneration-1.14.4-1.2.0.jar Solar Generation {solargeneration@1.2.0 DONE}
		CosmeticArmorReworked-1.14.4-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v1a DONE}
		overloadedarmorbar-3.0.0b.jar Overloaded Armor Bar {overloadedarmorbar@3.0.0b DONE}
		chesthopper-2.1.1.jar ChestHopper {chesthopper@v2.1.1 DONE}
		DefaultOptions_1.14.4-10.2.6.jar Default Options {defaultoptions@10.2.6 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['raziel23x'/43913, l='Raziel23x World', x=-280.69, y=65.85, z=352.75]]
	Data Packs: vanilla, mod:alchemistry, mod:alib, mod:angelring, mod:apotheosis, mod:appleskin, mod:attributefix, mod:bambooeverything, mod:bambooladders, mod:biomesoplenty, mod:buildinggadgets, mod:caelus, mod:campfiretorches, mod:carryon, mod:ceilingtorch, mod:charcoalblock, mod:charm, mod:chemlib, mod:chesthopper, mod:chickendropfeathersmod, mod:citadel, mod:clumps, mod:colossalchests, mod:colytra, mod:compatchedstorage, mod:compressed, mod:compressium, mod:computercraft, mod:container, mod:controlling, mod:corail_woodcutter, mod:cosmeticarmorreworked, mod:craftingstation, mod:craftingtweaks, mod:create, mod:cucumber, mod:cursedearth, mod:cyclic, mod:cyclopscore, mod:d2p, mod:dankstorage, mod:dcintegration, mod:defaultoptions, mod:defaultsettings, mod:dungeoncrawl, mod:easy_steel, mod:edibsgr, mod:edit_sign, mod:elevatorid, mod:elrolsutilities, mod:enchdesc, mod:enchxchg, mod:energeticsheep, mod:enviromats, mod:essentials, mod:everlastingabilities, mod:extcaves, mod:extraanvils, mod:f2l, mod:fastbench, mod:fastfurnace, mod:fastleafdecay, mod:firstaid, mod:flintblock, mod:fluidtank, mod:forbidden_arcanus, mod:forge, mod:ftbbackups, mod:gemsplusplus, mod:globaldatapack, mod:gobber2, mod:harvest, mod:inventorysorter, mod:ironchest, mod:ironjetpacks, mod:ironshulkerbox, mod:jei, mod:jeresources (incompatible), mod:kleeslabs, mod:llor, mod:lycanitesmobs, mod:mcjtylib, mod:metalbarrels, mod:minecolonies (incompatible), mod:modnametooltip, mod:moreprogression, mod:mousetweaks, mod:mysticalagriculture, mod:oreexcavation, mod:overloaded, mod:overloadedarmorbar, mod:particlefixes, mod:peanutmod, mod:pickletweaks, mod:placebo, mod:portality (incompatible), mod:powder_power, mod:quantumstorage, mod:randompatches, mod:randomthings, mod:reap, mod:refinedstorage, mod:rftoolsbase, mod:rftoolsbuilder, mod:rftoolspower, mod:rftoolsstorage, mod:rftoolsutility, mod:ring_of_attraction, mod:ring_of_blink, mod:ring_of_enderchest, mod:ring_of_growth, mod:ring_of_miner, mod:ring_of_repair, mod:ring_of_teleport, mod:ruins, mod:silentgear, mod:silentgems, mod:silentlib, mod:silents_mechanisms, mod:simpledivegear, mod:simplefarming, mod:simplylight, mod:snad, mod:solargeneration, mod:spiketraps, mod:stonechest, mod:storagedrawers, mod:storagenetwork, mod:structurize, mod:techemistry, mod:titanium (incompatible), mod:tombstone, mod:toolbelt, mod:torchbandolier, mod:torchbowmod, mod:torchmaster, mod:torchoptimizer, mod:tramplestopper, mod:travellersboots, mod:tubesreloaded, mod:upgrade_aquatic, mod:uppers, mod:upsizer, mod:usefulbackpacks, mod:uteamcore, mod:valkyrielib, mod:vampirism, mod:veggie_way, mod:voxelmap, mod:waila, mod:waterstrainer, mod:weapon_craftery, mod:woodenshears, mod:wooltostring, mod:wyrmroost, mod:xlfoodmod, mod:yamda, modpack:Custom_Recipe_Datapack.zip (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Elrol** [comment] 2019-11-04 02:46
I will take a look at fixing this presently, I will have an update tonight to have this fixed. Sorry for the issue.

**Comment by Elrol** [comment] 2019-11-04 03:01
Just made a hotfix, I did not run into the issue when testing, but looking back, it was a bit of missing code. To convert the player data from the old system to the new one, some things are moved over then removed, and if the old list is empty then it changes it to null. The issue is that when i was checking if the playerdata exitsted in the old method, it did not check for null, and that is what caused the issue. Just added a quick check to see. 

https://www.curseforge.com/minecraft/mc-mods/elrols-server-utilities/files/2821737

Please give that a test and if it solves the issue great, if not I will need to see the log and the report. It would be best to paste them on a site like https://pastebin.com/ and paste the link here instead. 

Sorry for the issue, and I hope that everything works out.

**Comment by Elrol** [comment] 2019-11-08 22:47
Going to assume that this has been fixed by the patch. If any other issue happen, let me know.

**Closed by Elrol** 2019-11-08 22:47 UTC
Labels: Response Needed, To-Do, bug
